name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          registry-url: 'https://registry.npmjs.org'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - run: pnpm install

      - run: pnpm build

      - name: Publish to npmjs
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
